#!/usr/bin/env bash
#  Bash Script to Create PID File and Handle Signals

# Create the PID file
echo $$ > /var/run/myscript.pid

# Define the signal handlers
trap "echo 'To infinity and beyond indefinitely'" SIGUSR1
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM

# Infinite loop
while true; do
    sleep 1
done