#!/usr/bin/env bash
# bash script to loop from 1 to 10 with conditions
count=1
while [ "$count" -le 10 ]
do
        if [ "$count" -eq 4 ]
        then
            echo "Bad luck"
        elif [ "$count" -eq 8 ]
        then
            echo "Good luck"
        else
            echo "Best School"
        fi
    count=$((count+1))
done