#!/usr/bin/env bash
# Bash Script to Display Time for 12 Hours and 59 Minutes

hour=0
minute=1

while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]; do
        echo "$minute"
        minute=$((minute+1))
    done
    hour=$((hour+1))
    minute=0
done
echo "Hour: 12"