#!/usr/bin/env bash
# Bash Script to Display Content of Current Directory

for file in *; do
    if [[ -f $file && $file != .* ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "- $name"
    fi
done